name: Unit tests for Kuva Geometry

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    #   - develop  # Temporarily disabled until first release
    paths:
      - 'kuva-geometry/**'
  push:
    branches:
      - main
    #   - develop  # Temporarily disabled until first release
    paths:
      - 'kuva-geometry/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.x

      - name: Install Poetry
        run: |
          pip install "poetry<2"
          poetry --version

      - name: Install project dependencies
        working-directory: ./kuva-geometry
        run: poetry install --no-root

      - name: Install package
        working-directory: ./kuva-geometry
        run: poetry install --no-interaction

      - name: Run tests
        working-directory: ./kuva-geometry
        run: poetry run pytest
