name: Unit tests for Kuva Reader

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    #   - develop  # Temporarily disabled until first release
    paths:
      - 'kuva-reader/**'
  push:
    branches:
      - main
    #   - develop  # Temporarily disabled until first release
    paths:
      - 'kuva-reader/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout out repository
        uses: actions/checkout@v3
        with:
          lfs: true  # Enable Git LFS

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          pip install "poetry<2"
          poetry --version

      - name: Install project dependencies
        working-directory: ./kuva-reader
        run: poetry install --no-root

      - name: Install package
        working-directory: ./kuva-reader
        run: poetry install --no-interaction

      - name: Run tests
        working-directory: ./kuva-reader
        run: poetry run pytest
