name: Unit tests for Kuva Reader

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    #   - develop  # Temporarily disabled until first release
    paths:
      - 'kuva-reader/**'
  push:
    branches:
      - main
    #   - develop  # Temporarily disabled until first release
    paths:
      - 'kuva-reader/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout out repository
        uses: actions/checkout@v3
        with:
          lfs: true  # Enable Git LFS

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        working-directory: ./kuva-geometry
        run: uv run pytest
